//  Error handling by try catch blocks

let a = 5;
let b = 6;
console.log("sum is :",a+b);

try{
    console.log("sum is :",a+c);
}catch(error){
    console.log(error);
}

console.log("sum is :",a);
console.log("sum is :",b);
console.log("substraction is :",a-b);